### PR TITLE
Housekeeping

### PR DESCRIPTION
**Pull request by bls1999**
Housekeeping on server/parts/Prizes.php

Added some comments and a couple of things that need to be fixed. Will add the missing sets (Santa, djinn, reindeer, crocodile, valentine, bunny) and more details to the comments later

### CODE REVIEW

**Comment by jacob-grahn** [comment]
Thanks! I’ll take a closer look at this soon. I’m traveling this weekend.

**Comment by bls1999** [comment]
Sure thing!  I have some more stuff to add anyway. :)

**Comment by bls1999** [comment]
@jacob-grahn Good idea! See my commits in #10

**Comment by bls1999** [comment]
@jacob-grahn I'll resubmit this, since I have file changes to Prizes.php anyway and the changes to pr2_moderation.php are outdated on this pull.  Feel free to close!

**Pull request closed without merging**
